### ISSUE TITLE
Autonumber seed isn't used - starts at 1

### ISSUE THREAD

**Issue by CREFaulk** [contactmayankp/AutoNumberUpdater#1]
Hi, I just saw this app right when I wanted this exact function! Unfortunately, my new autonumber field has a seed but the AutoNumberUpdater always starts with nextnumber of 1. 

This is with Dynamics 365 online and is a completely new field so if the current max value is checked and not the seed then this might be why.

A simple workaround was to create a new record so there's an existing value with the seed. After that the next number was the expected value.

Thanks!

**Comment by contactmayankp** [comment]
@CREFaulk  Thanks for your feedback and appreciate raising this issue, I already fixed this issue in my local now but I will release update on this soon (I am working on some other updates on this tool)

![image](https://user-images.githubusercontent.com/6472981/145690671-b9fdc546-903c-474f-a73c-b1870bb8f931.png)


I will close this issue once I release updated version of this tool...

Thanks
