### ISSUE TITLE
Unable to use tool - getting error when selecting auto number field

### ISSUE THREAD

**Issue by tmykhaylovsky** [contactmayankp/AutoNumberUpdater#6]
Unable to use tool - getting error when selecting auto number field

System.Exception: That was hard. Couldn't even guess what current SEQNUM is.
Numbered value for last created record is:  
LY2X1

Any ideas?

**Comment by crazykarl7** [comment]
I had gotten this error when a user had put a custom value into the autonumber field (it wasn't read only).  You can use sql4cds. something like select <field> from <table> where <field> not like '%-%'

**Comment by contactmayankp** [comment]
> LY2X1

This means there is record in your system which does not in same format as auto number format configured in this field... if you can fix this record(s) and then try again .. it should work.... 

let us know how you get on?

**Comment by contactmayankp** [comment]
@tmykhaylovsky  @crazykarl7  this issue has fixed now...
